language: go
go:
  - '1.8'
  - '1.9'
  - '1.10'
  - '1.11'
before_install:
  - go get -v github.com/google/go-querystring/query
  - go get -v github.com/h2non/gock
  - cp .env.dist .env
script: go test -v ./...
